/* Governance Blueprint Policy Registry: bilingual, read-only control catalogue with explicit governance metadata. */
import { ArrowUpRight, CalendarClock, ChevronRight, CircleCheck, ExternalLink, Filter, ShieldCheck, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { PortalShell, type Locale } from "@/components/PortalShell";
import { policyPacks, type Scope } from "@/data/policyPacks";

const copy = {
  en: { eyebrow: "POLICY REGISTRY / 03", title: <>Policy is not prose.<br />It is a <i style={{ color: "#dbe7e5" }}>versioned control surface.</i></>, lead: "A public, read-only control catalogue for AI-SDLC Spec Kit. Every record names the control intent, source pack, enforcement method, evidence, ownership, review cadence, and exception path.", status: "CURRENT BASELINE", filters: { all: "All scopes", command: "Command", spec: "Spec", graph: "Trace graph" }, scopes: { command: "Command", spec: "Specification", graph: "Artifact graph" }, stages: { build: "Build", specify: "Specify", validate: "Validate" }, details: "Policy detail", rules: "Rule manifest", scope: "Applies to", method: "Enforcement", version: "Version", lifecycle: "Lifecycle stage", state: "State", intent: "Control intent", owner: "Control owner", cadence: "Review cadence", evidence: "Evidence expected", exceptions: "Exception protocol", source: "Source pack", docs: "Open related Docs", anatomy: "Registry record anatomy", anatomyLead: "These fields remain stable as the Registry grows from the public baseline into a signed Kit Registry.", recordFields: [["Identity", "Stable policy ID and bilingual control title."], ["Source", "Pack path, version, rule manifest, and compatibility."], ["Governance", "Owner, status, review cadence, and exception protocol."], ["Proof", "Declared enforcement method and evidence expected for a release."], ["Trace", "Links back to lifecycle Docs and related controls."]], note: "Registry boundary", noteText: "This is a browse surface, not a policy editor. Authoring, approval, signing, and distribution belong to the future Kit Registry control plane." },
  vi: { eyebrow: "POLICY REGISTRY / 03", title: <>Policy không phải văn xuôi.<br />Nó là một <i style={{ color: "#dbe7e5" }}>control surface có version.</i></>, lead: "Control catalogue public, chỉ đọc cho AI-SDLC Spec Kit. Mỗi record nêu control intent, pack nguồn, enforcement, evidence, ownership, review cadence và exception path.", status: "CURRENT BASELINE", filters: { all: "Tất cả scope", command: "Command", spec: "Spec", graph: "Trace graph" }, scopes: { command: "Command", spec: "Specification", graph: "Artifact graph" }, stages: { build: "Build", specify: "Specify", validate: "Validate" }, details: "Chi tiết policy", rules: "Rule manifest", scope: "Phạm vi áp dụng", method: "Enforcement", version: "Phiên bản", lifecycle: "Giai đoạn vòng đời", state: "Trạng thái", intent: "Mục tiêu kiểm soát", owner: "Chủ sở hữu control", cadence: "Chu kỳ review", evidence: "Evidence mong đợi", exceptions: "Quy trình exception", source: "Pack nguồn", docs: "Mở Docs liên quan", anatomy: "Cấu trúc record Registry", anatomyLead: "Các field này giữ ổn định khi Registry phát triển từ public baseline sang Kit Registry có ký số.", recordFields: [["Định danh", "Policy ID ổn định và control title song ngữ."], ["Nguồn", "Pack path, version, rule manifest và compatibility."], ["Governance", "Owner, status, review cadence và exception protocol."], ["Bằng chứng", "Enforcement method đã khai báo và evidence cần cho release."], ["Trace", "Link ngược về lifecycle Docs và control liên quan."]], note: "Ranh giới Registry", noteText: "Đây là browse surface, không phải policy editor. Authoring, approval, signing và distribution thuộc về Kit Registry control plane trong tương lai." },
} as const;

export default function PolicyRegistry() { return <PortalShell route="policies">{(locale) => <RegistryContent locale={locale} />}</PortalShell>; }

function RegistryContent({ locale }: { locale: Locale }) {
  const [scope, setScope] = useState<"all" | Scope>("all");
  const [selectedId, setSelectedId] = useState("AGENT-LAUNCH");
  const t = copy[locale];
  const selected = policyPacks.find((pack) => pack.id === selectedId) ?? policyPacks[0];
  const filtered = useMemo(() => policyPacks.filter((pack) => scope === "all" || pack.scope === scope), [scope]);
  const governance = [[t.owner, selected.owner[locale], <UserRound size={15} key="owner" />], [t.cadence, selected.cadence[locale], <CalendarClock size={15} key="cadence" />], [t.evidence, selected.evidence[locale], <ShieldCheck size={15} key="evidence" />], [t.exceptions, selected.exceptions[locale], <CircleCheck size={15} key="exceptions" />]] as const;

  return <div className="registry-page">
    <section className="registry-hero"><div className="registry-grid" aria-hidden="true" /><div><div className="eyebrow"><span className="pulse-line" /> {t.eyebrow}</div><h1>{t.title}</h1><p>{t.lead}</p></div><div className="registry-status"><span className="verify-dot" /><span>{t.status}</span><strong>{policyPacks.length} PACKS / v1.0.0</strong></div></section>
    <section className="registry-workbench"><div className="registry-toolbar"><div><span className="mono-label"><Filter size={13} /> {locale === "en" ? "FILTER BY SCOPE" : "LỌC THEO SCOPE"}</span><div className="filter-tabs">{(["all", "command", "spec", "graph"] as const).map((value) => <button key={value} className={scope === value ? "is-active" : ""} onClick={() => { setScope(value); if (value !== "all" && selected.scope !== value) setSelectedId(policyPacks.find((pack) => pack.scope === value)?.id ?? selectedId); }}>{t.filters[value]}</button>)}</div></div><a href="/docs" className="text-button">{t.docs} <ArrowUpRight size={15} /></a></div>
      <div className="registry-layout"><div className="registry-list">{filtered.map((pack, index) => <button key={pack.id} className={selected.id === pack.id ? "is-selected" : ""} onClick={() => setSelectedId(pack.id)}><span>0{index + 1}</span><div><code>{pack.id}</code><strong>{pack.title[locale]}</strong><em>{pack.file}</em></div><ChevronRight size={17} /></button>)}</div>
        <article className="pack-detail"><div className="detail-top"><div><span className="mono-label">{t.details}</span><h2>{selected.title[locale]}</h2></div><div className="detail-id"><ShieldCheck size={17} /><code>{selected.id}</code></div></div><p className="detail-summary">{selected.summary[locale]}</p><div className="detail-meta detail-meta-expanded"><div><span>{t.version}</span><strong>{selected.version}</strong></div><div><span>{t.state}</span><strong>{selected.status}</strong></div><div><span>{t.scope}</span><strong>{t.scopes[selected.scope]}</strong></div><div><span>{t.lifecycle}</span><strong>{t.stages[selected.stage]}</strong></div><div><span>{t.method}</span><strong>{selected.method[locale]}</strong></div><div><span>{t.source}</span><strong>{selected.file}</strong></div></div><div className="control-intent"><span className="mono-label">{t.intent}</span><p>{selected.intent[locale]}</p></div><div className="detail-rules"><div className="detail-rule-head"><span>{t.rules}</span><span>{selected.rules.length} {locale === "en" ? "declared checks" : "check đã khai báo"}</span></div>{selected.rules.map((rule) => <div key={rule.id} className="detail-rule"><CircleCheck size={15} /><code>{rule.id}</code><span className={`severity ${rule.severity}`}>{rule.severity}</span><p>{rule.message[locale]}</p></div>)}</div><div className="governance-grid">{governance.map(([label, value, icon]) => <div key={label}><span>{icon}{label}</span><p>{value}</p></div>)}</div><div className="registry-detail-actions"><a href={`/policies/${selected.slug}`} className="underlined-button">{locale === "en" ? "Open detailed dossier" : "Mở hồ sơ chi tiết"} <ExternalLink size={15} /></a><a href={`/docs#${selected.docsAnchor}`} className="underlined-button">{t.docs} <ArrowUpRight size={15} /></a></div></article>
      </div>
    </section>
    <section className="registry-anatomy"><div><span className="mono-label">{t.anatomy}</span><p>{t.anatomyLead}</p></div><div className="anatomy-table">{t.recordFields.map(([label, value], index) => <div key={label}><span>{String(index + 1).padStart(2, "0")}</span><strong>{label}</strong><p>{value}</p></div>)}</div></section>
    <section className="registry-note"><div><span className="mono-label">{t.note}</span><p>{t.noteText}</p></div><a href="https://github.com/xdev-ai/ai-sdlc" target="_blank" rel="noreferrer" className="underlined-button">GitHub <ArrowUpRight size={15} /></a></section>
  </div>;
}
