/* Governance Blueprint Policy Registry: bilingual, read-only control catalogue with explicit governance metadata. */
import { ArrowUpRight, CalendarClock, ChevronRight, CircleCheck, Filter, ShieldCheck, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { PortalShell, type Locale } from "@/components/PortalShell";

type Scope = "command" | "spec" | "graph";
type Stage = "build" | "specify" | "validate";
type Bilingual = { en: string; vi: string };
type Rule = { id: string; severity: "error" | "warning"; en: string; vi: string };
type Pack = {
  id: string; file: string; scope: Scope; stage: Stage; version: string; status: "active"; docsAnchor: string;
  rules: Rule[]; title: Bilingual; summary: Bilingual; intent: Bilingual; method: Bilingual; owner: Bilingual; cadence: Bilingual; evidence: Bilingual; exceptions: Bilingual;
};

const packs: Pack[] = [
  { id: "AGENT-LAUNCH", file: "agent-launch.yml", scope: "command", stage: "build", version: "v1.0.0", status: "active", docsAnchor: "validation", title: { en: "Pinned agent launch", vi: "Agent launch được pin" }, summary: { en: "Makes model selection and verified launch constraints machine-checkable.", vi: "Biến model selection và launch constraint đã verify thành thứ máy có thể kiểm tra." }, intent: { en: "Prevent undocumented model and unsafe command launch drift.", vi: "Ngăn model không được khai báo và command launch không an toàn bị drift." }, method: { en: "Command definition lint", vi: "Lint command definition" }, owner: { en: "Platform control owner", vi: "Chủ sở hữu control của platform" }, cadence: { en: "Review with every Kit release", vi: "Review theo mỗi Kit release" }, evidence: { en: "Validated command manifest", vi: "Command manifest đã validate" }, exceptions: { en: "Named owner, rationale, approver, expiry", vi: "Owner rõ ràng, rationale, approver, expiry" }, rules: [{ id: "LAUNCH-001", severity: "error", en: "Automated commands must pin --model.", vi: "Automated command phải pin --model." }, { id: "LAUNCH-002", severity: "error", en: "Kit commands must not use --bare.", vi: "Kit command không được dùng --bare." }] },
  { id: "SPEC-STRUCT", file: "spec-structure.yml", scope: "spec", stage: "specify", version: "v1.0.0", status: "active", docsAnchor: "kit", title: { en: "Structured specification entry", vi: "Cổng vào specification có cấu trúc" }, summary: { en: "Keeps incoming Markdown specifications identifiable, shaped, and usable by downstream validation.", vi: "Giữ Markdown specification đầu vào có định danh, hình dạng và khả năng dùng cho validation phía sau." }, intent: { en: "Make every eligible specification reviewable before implementation work begins.", vi: "Đảm bảo specification đủ điều kiện có thể review trước khi bắt đầu implementation." }, method: { en: "Specification validation", vi: "Specification validation" }, owner: { en: "Product and engineering control owner", vi: "Chủ sở hữu control product và engineering" }, cadence: { en: "Review with template or schema change", vi: "Review khi template hoặc schema thay đổi" }, evidence: { en: "Specification validation result", vi: "Kết quả specification validation" }, exceptions: { en: "Explicit waiver with scope and expiry", vi: "Waiver tường minh có scope và expiry" }, rules: [{ id: "SPEC-STRUCT-001", severity: "error", en: "Frontmatter must include id.", vi: "Frontmatter phải có id." }, { id: "SPEC-STRUCT-002", severity: "error", en: "ID must match the artifact grammar.", vi: "ID phải khớp artifact grammar." }, { id: "SPEC-STRUCT-003", severity: "error", en: "Description must be present and non-empty.", vi: "Description phải tồn tại và không rỗng." }, { id: "SPEC-STRUCT-004", severity: "warning", en: "Acceptance Criteria is recommended.", vi: "Khuyến nghị Acceptance Criteria." }, { id: "SPEC-STRUCT-005", severity: "warning", en: "Non-functional Requirements is recommended.", vi: "Khuyến nghị Non-functional Requirements." }, { id: "SPEC-STRUCT-006", severity: "error", en: "Artifact IDs must be unique across files.", vi: "Artifact ID phải unique giữa các file." }] },
  { id: "TRACE", file: "traceability.yml", scope: "graph", stage: "validate", version: "v1.0.0", status: "active", docsAnchor: "lifecycle", title: { en: "Traceability invariants", vi: "Bất biến traceability" }, summary: { en: "Enforces key edges across the artifact graph so evidence is not a post-release reconstruction.", vi: "Enforce các edge quan trọng trong artifact graph để evidence không phải được dựng lại sau release." }, intent: { en: "Preserve accountable links from business intent through verification evidence.", vi: "Giữ liên kết có trách nhiệm từ business intent đến verification evidence." }, method: { en: "Artifact graph validation", vi: "Artifact graph validation" }, owner: { en: "Delivery assurance control owner", vi: "Chủ sở hữu control delivery assurance" }, cadence: { en: "Review at release-gate changes", vi: "Review khi release gate thay đổi" }, evidence: { en: "Resolved artifact graph and linked tests", vi: "Đồ thị artifact resolve được và test đã link" }, exceptions: { en: "Approved, time-bounded trace gap record", vi: "Record trace gap được duyệt và có thời hạn" }, rules: [{ id: "TRACE-001", severity: "error", en: "Each business rule needs a verified_by edge to a test case.", vi: "Mỗi business rule cần edge verified_by đến test case." }, { id: "TRACE-002", severity: "error", en: "Each requirement needs a refines edge from a specification.", vi: "Mỗi requirement cần edge refines từ specification." }, { id: "TRACE-003", severity: "warning", en: "Acceptance criteria should be tracked by an implementation task.", vi: "Acceptance criteria nên được tracked_by bởi implementation task." }, { id: "TRACE-004", severity: "error", en: "Every referenced ID must resolve in the run.", vi: "Mọi referenced ID phải resolve trong run." }] },
];

const copy = {
  en: { eyebrow: "POLICY REGISTRY / 03", title: <>Policy is not prose.<br />It is a <i style={{ color: "#dbe7e5" }}>versioned control surface.</i></>, lead: "A public, read-only control catalogue for AI-SDLC Spec Kit. Every record names the control intent, source pack, enforcement method, evidence, ownership, review cadence, and exception path.", status: "CURRENT BASELINE", filters: { all: "All scopes", command: "Command", spec: "Spec", graph: "Trace graph" }, scopes: { command: "Command", spec: "Specification", graph: "Artifact graph" }, stages: { build: "Build", specify: "Specify", validate: "Validate" }, details: "Policy detail", rules: "Rule manifest", scope: "Applies to", method: "Enforcement", version: "Version", lifecycle: "Lifecycle stage", state: "State", intent: "Control intent", owner: "Control owner", cadence: "Review cadence", evidence: "Evidence expected", exceptions: "Exception protocol", source: "Source pack", docs: "Open related Docs", anatomy: "Registry record anatomy", anatomyLead: "These fields remain stable as the Registry grows from the public baseline into a signed Kit Registry.", recordFields: [["Identity", "Stable policy ID and bilingual control title."], ["Source", "Pack path, version, rule manifest, and compatibility."], ["Governance", "Owner, status, review cadence, and exception protocol."], ["Proof", "Declared enforcement method and evidence expected for a release."], ["Trace", "Links back to lifecycle Docs and related controls."]], note: "Registry boundary", noteText: "This is a browse surface, not a policy editor. Authoring, approval, signing, and distribution belong to the future Kit Registry control plane." },
  vi: { eyebrow: "POLICY REGISTRY / 03", title: <>Policy không phải văn xuôi.<br />Nó là một <i style={{ color: "#dbe7e5" }}>control surface có version.</i></>, lead: "Control catalogue public, chỉ đọc cho AI-SDLC Spec Kit. Mỗi record nêu control intent, pack nguồn, enforcement, evidence, ownership, review cadence và exception path.", status: "CURRENT BASELINE", filters: { all: "Tất cả scope", command: "Command", spec: "Spec", graph: "Trace graph" }, scopes: { command: "Command", spec: "Specification", graph: "Artifact graph" }, stages: { build: "Build", specify: "Specify", validate: "Validate" }, details: "Chi tiết policy", rules: "Rule manifest", scope: "Phạm vi áp dụng", method: "Enforcement", version: "Phiên bản", lifecycle: "Giai đoạn vòng đời", state: "Trạng thái", intent: "Mục tiêu kiểm soát", owner: "Chủ sở hữu control", cadence: "Chu kỳ review", evidence: "Evidence mong đợi", exceptions: "Quy trình exception", source: "Pack nguồn", docs: "Mở Docs liên quan", anatomy: "Cấu trúc record Registry", anatomyLead: "Các field này giữ ổn định khi Registry phát triển từ public baseline sang Kit Registry có ký số.", recordFields: [["Định danh", "Policy ID ổn định và control title song ngữ."], ["Nguồn", "Pack path, version, rule manifest và compatibility."], ["Governance", "Owner, status, review cadence và exception protocol."], ["Bằng chứng", "Enforcement method đã khai báo và evidence cần cho release."], ["Trace", "Link ngược về lifecycle Docs và control liên quan."]], note: "Ranh giới Registry", noteText: "Đây là browse surface, không phải policy editor. Authoring, approval, signing và distribution thuộc về Kit Registry control plane trong tương lai." },
} as const;

export default function PolicyRegistry() { return <PortalShell route="policies">{(locale) => <RegistryContent locale={locale} />}</PortalShell>; }

function RegistryContent({ locale }: { locale: Locale }) {
  const [scope, setScope] = useState<"all" | Scope>("all");
  const [selectedId, setSelectedId] = useState("AGENT-LAUNCH");
  const t = copy[locale];
  const selected = packs.find((pack) => pack.id === selectedId) ?? packs[0];
  const filtered = useMemo(() => packs.filter((pack) => scope === "all" || pack.scope === scope), [scope]);
  const governance = [[t.owner, selected.owner[locale], <UserRound size={15} key="owner" />], [t.cadence, selected.cadence[locale], <CalendarClock size={15} key="cadence" />], [t.evidence, selected.evidence[locale], <ShieldCheck size={15} key="evidence" />], [t.exceptions, selected.exceptions[locale], <CircleCheck size={15} key="exceptions" />]] as const;

  return <div className="registry-page">
    <section className="registry-hero"><div className="registry-grid" aria-hidden="true" /><div><div className="eyebrow"><span className="pulse-line" /> {t.eyebrow}</div><h1>{t.title}</h1><p>{t.lead}</p></div><div className="registry-status"><span className="verify-dot" /><span>{t.status}</span><strong>{packs.length} PACKS / v1.0.0</strong></div></section>
    <section className="registry-workbench"><div className="registry-toolbar"><div><span className="mono-label"><Filter size={13} /> {locale === "en" ? "FILTER BY SCOPE" : "LỌC THEO SCOPE"}</span><div className="filter-tabs">{(["all", "command", "spec", "graph"] as const).map((value) => <button key={value} className={scope === value ? "is-active" : ""} onClick={() => { setScope(value); if (value !== "all" && selected.scope !== value) setSelectedId(packs.find((pack) => pack.scope === value)?.id ?? selectedId); }}>{t.filters[value]}</button>)}</div></div><a href="/docs" className="text-button">{t.docs} <ArrowUpRight size={15} /></a></div>
      <div className="registry-layout"><div className="registry-list">{filtered.map((pack, index) => <button key={pack.id} className={selected.id === pack.id ? "is-selected" : ""} onClick={() => setSelectedId(pack.id)}><span>0{index + 1}</span><div><code>{pack.id}</code><strong>{pack.title[locale]}</strong><em>{pack.file}</em></div><ChevronRight size={17} /></button>)}</div>
        <article className="pack-detail"><div className="detail-top"><div><span className="mono-label">{t.details}</span><h2>{selected.title[locale]}</h2></div><div className="detail-id"><ShieldCheck size={17} /><code>{selected.id}</code></div></div><p className="detail-summary">{selected.summary[locale]}</p><div className="detail-meta detail-meta-expanded"><div><span>{t.version}</span><strong>{selected.version}</strong></div><div><span>{t.state}</span><strong>{selected.status}</strong></div><div><span>{t.scope}</span><strong>{t.scopes[selected.scope]}</strong></div><div><span>{t.lifecycle}</span><strong>{t.stages[selected.stage]}</strong></div><div><span>{t.method}</span><strong>{selected.method[locale]}</strong></div><div><span>{t.source}</span><strong>{selected.file}</strong></div></div><div className="control-intent"><span className="mono-label">{t.intent}</span><p>{selected.intent[locale]}</p></div><div className="detail-rules"><div className="detail-rule-head"><span>{t.rules}</span><span>{selected.rules.length} {locale === "en" ? "declared checks" : "check đã khai báo"}</span></div>{selected.rules.map((rule) => <div key={rule.id} className="detail-rule"><CircleCheck size={15} /><code>{rule.id}</code><span className={`severity ${rule.severity}`}>{rule.severity}</span><p>{rule[locale]}</p></div>)}</div><div className="governance-grid">{governance.map(([label, value, icon]) => <div key={label}><span>{icon}{label}</span><p>{value}</p></div>)}</div><a href={`/docs#${selected.docsAnchor}`} className="underlined-button">{t.docs} <ArrowUpRight size={15} /></a></article>
      </div>
    </section>
    <section className="registry-anatomy"><div><span className="mono-label">{t.anatomy}</span><p>{t.anatomyLead}</p></div><div className="anatomy-table">{t.recordFields.map(([label, value], index) => <div key={label}><span>{String(index + 1).padStart(2, "0")}</span><strong>{label}</strong><p>{value}</p></div>)}</div></section>
    <section className="registry-note"><div><span className="mono-label">{t.note}</span><p>{t.noteText}</p></div><a href="https://github.com/xdev-ai/ai-sdlc" target="_blank" rel="noreferrer" className="underlined-button">GitHub <ArrowUpRight size={15} /></a></section>
  </div>;
}
