"use client";
/* Policy dossier detail: read-only control surface for one AI-SDLC rule pack. */
import { ArrowLeft, ArrowUpRight, BadgeCheck, CalendarClock, CircleCheck, FileCode2, Link2, ShieldCheck, UserRound } from "lucide-react";
import { PortalShell, type Locale } from "@/components/PortalShell";
import { findPolicyPack, type PolicyPack } from "@/data/policyPacks";
const copy = { en: { eyebrow: "POLICY DOSSIER / 03", back: "Back to Policy Registry", source: "Source pack", contract: "Declared contract", applies: "Applies to", intent: "Control intent", method: "Enforcement", rules: "Rule ledger", arguments: "Declared arguments", remediation: "Remediation route", governance: "Governance record", owner: "Control owner", cadence: "Review cadence", evidence: "Evidence expected", exceptions: "Exception protocol", docs: "Open related Docs", copy: "Copy link", missing: "Policy record not found", missingText: "This path does not match a published policy pack in the current baseline.", registry: "Open registry" }, vi: { eyebrow: "HỒ SƠ POLICY / 03", back: "Quay lại Kho chính sách", source: "Pack nguồn", contract: "Contract đã khai báo", applies: "Phạm vi áp dụng", intent: "Mục tiêu kiểm soát", method: "Enforcement", rules: "Sổ cái rule", arguments: "Arguments đã khai báo", remediation: "Lộ trình remediation", governance: "Record governance", owner: "Chủ sở hữu control", cadence: "Chu kỳ review", evidence: "Evidence mong đợi", exceptions: "Quy trình exception", docs: "Mở Docs liên quan", copy: "Sao chép liên kết", missing: "Không tìm thấy record policy", missingText: "Đường dẫn này không khớp với policy pack đã publish trong baseline hiện tại.", registry: "Mở kho chính sách" } } as const;
export default function PolicyDetailClient({ pack }: { pack: PolicyPack }) {  return <PortalShell route="policies">{(locale) => <PolicyDetailContent locale={locale} slug={pack.slug} />}</PortalShell>; }
function PolicyDetailContent({ locale, slug }: { locale: Locale; slug?: string }) {
  const t = copy[locale]; const pack = findPolicyPack(slug); const copyRoute = async () => { await navigator.clipboard?.writeText(window.location.href); };
  if (!pack) return <div className="policy-detail-page"><section className="policy-detail-missing"><ShieldCheck size={30} /><span className="mono-label">404 / POLICY ROUTE</span><h1>{t.missing}</h1><p>{t.missingText}</p><a className="ink-button" href="/policies">{t.registry} <ArrowUpRight size={16} /></a></section></div>;
  const governance = [[t.owner, pack.owner[locale], <UserRound size={15} key="owner" />], [t.cadence, pack.cadence[locale], <CalendarClock size={15} key="cadence" />], [t.evidence, pack.evidence[locale], <ShieldCheck size={15} key="evidence" />], [t.exceptions, pack.exceptions[locale], <CircleCheck size={15} key="exceptions" />]] as const;
  return <div className="policy-detail-page"><section className="policy-detail-hero"><div className="policy-detail-grid" aria-hidden="true" /><div><a href="/policies" className="policy-back"><ArrowLeft size={15} /> {t.back}</a><div className="eyebrow"><span className="pulse-line" /> {t.eyebrow}</div><h1>{pack.title[locale]}</h1><p>{pack.summary[locale]}</p><div className="policy-detail-actions"><button onClick={copyRoute}><Link2 size={15} /> {t.copy}</button><a href={`/docs#${pack.docsAnchor}`}><ArrowUpRight size={15} /> {t.docs}</a></div></div><div className="policy-identity-card"><BadgeCheck size={22} /><code>{pack.id}</code><span>{pack.version}</span><strong>{pack.status.toUpperCase()}</strong><i className="verify-dot" /></div></section><section className="policy-detail-workspace"><article className="policy-contract-card"><div className="policy-block-head"><span className="mono-label">{t.contract}</span><code>{pack.file}</code></div><p>{pack.description[locale]}</p><div className="policy-source-grid"><div><span>{t.source}</span><strong>{pack.sourcePath}</strong></div><div><span>{t.applies}</span><strong>{pack.appliesTo.join(", ")}</strong></div><div><span>{t.method}</span><strong>{pack.method[locale]}</strong></div><div><span>{locale === "en" ? "Lifecycle stage" : "Giai đoạn vòng đời"}</span><strong>{pack.stage}</strong></div></div></article><div className="policy-proof-rail" aria-hidden="true"><span>01</span><i /><span>02</span><i /><span>03</span></div><article className="policy-intent-card"><span className="mono-label">{t.intent}</span><p>{pack.intent[locale]}</p><FileCode2 size={22} /></article><section className="policy-rule-ledger"><div className="policy-block-head"><span className="mono-label">{t.rules}</span><strong>{pack.rules.length} {locale === "en" ? "declared checks" : "check đã khai báo"}</strong></div>{pack.rules.map((rule, index) => <article key={rule.id} id={rule.id.toLowerCase()} className="policy-rule-record"><div className="policy-rule-number">{String(index + 1).padStart(2, "0")}</div><div className="policy-rule-main"><div><code>{rule.id}</code><span className={`severity ${rule.severity}`}>{rule.severity}</span></div><p>{rule.message[locale]}</p><div className="policy-check-kind"><span>CHECK</span><strong>{rule.check}</strong></div>{rule.arguments.length > 0 && <div className="policy-arguments"><span>{t.arguments}</span><div>{rule.arguments.map(([key, value]) => <code key={key}>{key}: <b>{value}</b></code>)}</div></div>}</div><div className="policy-remediation"><span>{t.remediation}</span><p>{rule.remediation[locale]}</p></div></article>)}</section><section className="policy-governance"><div className="policy-block-head"><span className="mono-label">{t.governance}</span><i className="verify-dot" /></div><div>{governance.map(([label, value, icon]) => <article key={label}><span>{icon}{label}</span><p>{value}</p></article>)}</div></section></section></div>;
}
